sudo: false

services:
  - docker

language: java

cache:
  directories:
    - $HOME/.m2/repository

jdk:
  - oraclejdk8

before_script:
  - "docker run -d -v \"$(pwd)/kannel.conf:/etc/kannel/kannel.conf\" -v \"$(pwd)/supervisord.conf:/etc/supervisor/conf.d/supervisord.conf\" --name kannel -p \"12000:12000\" -p \"12001:12001\" --add-host \"SMSC_HOST:$(ip route show 0.0.0.0/0 | grep -Eo 'via \\S+' | awk '{ print $2 }')\" bulktrade/kannel:r5159"
script:
  - "mvn verify -B"
after_success:
  - "mvn jacoco:report coveralls:report"