sudo: false

services:
  - docker

language: java

cache:
  directories:
    - $HOME/.m2/repository

jdk:
  - oraclejdk8

before_script:
  - "docker run -d -v \"$(pwd)/kannel.conf:/etc/kannel/kannel.conf\" -v \"$(pwd)/supervisord.conf:/etc/supervisor/conf.d/supervisord.conf\" --name kannel --hostname kannel -p \"12000:12000\" -p \"12001:12001\" --add-host \"SMSC_HOST:jannel\" bulktrade/kannel:r5159"
script:
  - "docker run -it --rm --name jannel  --hostname jannel --link kannel -v \"$(pwd):/usr/src/mymaven\" -w /usr/src/mymaven maven:3.2-jdk-7 mvn clean verify -B"
after_success:
  - "mvn jacoco:report coveralls:report"