sudo: true

services:
  - docker

language: java

cache:
  directories:
    - $HOME/.m2/repository

jdk:
  - oraclejdk8

before_install:
  - "sudo apt-get update"
  - "sudo apt-get install -o Dpkg::Options::=\"--force-confold\" --force-yes -y docker-engine"
before_script:
  - "docker network create --driver bridge it"
  - "docker run -d -v \"$(pwd)/kannel.conf:/etc/kannel/kannel.conf\" -v \"$(pwd)/supervisord.conf:/etc/supervisor/conf.d/supervisord.conf\" --name kannel --hostname kannel --net it bulktrade/kannel:r5159"
script:
  - "docker run -it --rm --name jannel --hostname jannel -v \"$(pwd):/usr/src/mymaven\" -v \"$HOME/.m2:/root/.m2\" -w /usr/src/mymaven -e \"KANNEL_HOST=kannel\" --net it maven:3.2-jdk-8 mvn clean verify -B"
after_success:
  - "sudo chown -R travis target"
  - "mvn jacoco:report coveralls:report"
after_script:
  - "docker rm -f kannel"
  - "docker network rm it"